name: publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          scope: '@suzulabo'
          always-auth: true
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm test

      - run: pnpm publish -r --dry-run
        if: github.ref == 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

      - run: pnpm publish -r --no-git-checks --tag test --dry-run
        if: github.ref != 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
